services:
  cheburgram-server:
    build: .
    container_name: cheburgram-server
    restart: unless-stopped
    ports:
      - "7878:7878/tcp"   # TCP Signaling
      - "7879:7879/udp"   # UDP Media Relay
    volumes:
      - cheburgram-data:/data   # реестр пользователей переживает пересоздание контейнера
    environment:
      - RUST_LOG=info

volumes:
  cheburgram-data:
