[package]
name = "cheburgram-audio"
version.workspace = true
edition.workspace = true

[dependencies]
cheburgram-protocol = { path = "../protocol" }
cpal.workspace = true
audiopus.workspace = true
audiopus_sys.workspace = true
rubato.workspace = true
ringbuf.workspace = true
anyhow.workspace = true
tracing.workspace = true
chacha20poly1305.workspace = true
nnnoiseless.workspace = true
minimp3.workspace = true



