[package]
name = "cheburgram-server"
version.workspace = true
edition.workspace = true

[dependencies]
cheburgram-protocol = { path = "../protocol" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
